import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#94643ef8] to-[#1d0b31] min-h-screen`}>
        <div className="max-w-[80%] mx-auto p-4 overflow-hidden ">
            <Navbar />
          <div className="backdrop-blur-2xl bg-white/10 border border-white/40 shadow-lg rounded-2xl p-6 my-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
